development: &sandbox # change to your own
  username: matjoh_1328483934_biz_api1.gmail.com
  password: 1328483955
  signature: AtrWm8sMsXwZtKZ5GIEnOIvfnA8NAoNZBN0I6w7dPf4JWFTpzXfjeiqE
  sandbox: true

test:
  <<: *sandbox

production: &production
  username: SET_YOUR_OWN
  password: SET_YOUR_OWN
  signature: SET_YOUR_OWN
  sandbox: false